server:
  port: 8080

spring:
  application:
    name: sofademo-facade
  cloud:
    consul:
      enable: true
      host: localhost
      port: 8500
      discovery:
        register: true
        hostname: localhost
        serviceName: ${spring.application.name}
        healthCheckPath: /health
        healthCheckInterval: 15s
        tags: urlprefix-/${spring.application.name}
        instanceId: ${spring.application.name}-${random.value}